title: Crossword Solver
hero_image: images/banner.png
description:
version: 4
listed: false
copyedit: false
last_tested: "2018-12-06"
steps:
  - title: Introduction
  - title: Using the Dictionary
  - title: Reading a Clue
  - title: Using Wolfram Alpha to Analyse Input
  - title: Combining Input Fields and Wolfram Alpha Code
  - title: Building an Interface