title: Crossword solver
hero_image: images/banner.png
description:
version: 4
listed: false
copyedit: false
last_tested: "2018-12-06"
steps:
  - title: Introduction
  - title: Using the dictionary
  - title: Reading a clue
  - title: Using Wolfram Alpha to analyse input
  - title: Building an interface
